// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Content        string     `json:"content"`
	CommentsActive bool       `json:"commentsActive"`
	CreatedAt      string     `json:"createdAt"`
	UpdatedAt      string     `json:"updatedAt"`
	Comments       []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
